#!/usr/bin/env bash
# Creates the file /var/run/myscript.pid containing its PID

PIDFILE="/var/run/myscript.pid"

# Write the script's PID
echo "$$" > "$PIDFILE"

# Signal handlers
trap 'echo "I hate the kill command"; rm -f "$PIDFILE"; exit' SIGTERM
trap 'echo "Y U no love me?!";' SIGINT
trap 'rm -f "$PIDFILE"; exit' SIGQUIT

# Infinite loop
while true
do
    echo "To infinity and beyond"
    sleep 2
done
